name: V8 Build

on: workflow_dispatch
              
jobs:
    build:
        name: Build V8 for ${{ matrix.platform }}
        strategy:
            matrix:
                platform: [ubuntu-18.04]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 1
            - name: Build V8 linux
              if: matrix.platform == 'ubuntu-18.04'
              run: cd deps && ./build.py --no-clang
            - name: Build V8 macOS
              if: matrix.platform == 'macos-latest'
              run: cd deps && ./build.py
            - name: Upload libv8.a
              uses: actions/upload-artifact@v2
              with:
                name: linux_x86_64-libv8.a
                path: deps/linux_x86_64/libv8.a
